set -g default-terminal "screen-256color"
set -g status-bg orange

# source le fichier de config de tmux
bind r source-file ~/.tmux.conf

# split
bind v split-window -h -c "#{pane_current_path}"
bind b split-window -v -c "#{pane_current_path}"

# new window
bind c new-window -c "#{pane_current_path}"

# hjkl pour naviguer entre les fenetres
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# augmente le temps pour saisir le numéro du panes lors de la commade C-b q x
set -g display-panes-time 2000

# vi binding en mode copy
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# pour pouvoir scroller dans l'historique du terminal
#set -g mouse on
